### ISSUE TITLE
Cannot run yarn - following contributing.md directions

### ISSUE THREAD

**Issue by Julian-dev28** [ApeSwapFinance/apeswap-dex#39]
**Bug Description**
A clear and concise description of the bug.

error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".

**Steps to Reproduce**

1. clone repository 
2. CLI : yarn

**Expected Behavior**
Yarn updates packages
<img width="671" alt="Screen Shot 2021-03-29 at 9 42 08 AM" src="https://user-images.githubusercontent.com/73849597/112870419-0b4a7580-9073-11eb-96a6-4f62ecdd7262.png">
<img width="676" alt="Screen Shot 2021-03-29 at 9 42 50 AM" src="https://user-images.githubusercontent.com/73849597/112870520-26b58080-9073-11eb-9e43-c65a388dd923.png">

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by dracmic** [comment]
Hey guys it appears that npm package it isn't public ... So I think the request should be... Hey Mr. Owner can you please make the uikit public?

**Comment by ape-swap** [comment]
Thanks for reporting and asking this. `ApeSwapFinance/apeswap-uikit` has been made public now. That should resolve the issue
